/**
 * Historic Bath data file.
 *
 * @copyright   2015 dodify Ltd.
 * @license     See LICENSE in repository root
 */

var photos = [
  { lat: 51.379335, lng: -2.358434, file: "3.jpg", title: "Pulteney Bridge", description: "Pulteney Bridge was designed by Robert Adam and built between 1769 and 1774. Its Palladian style shows a distinct contemporary Italian influence (with some marked similarities to the Rialto Bridge in Venice). Today, the bridge is lined with shops, and the river cannot be seen from it. Most pedestrians crossing the bridge have no clue it is a bridge. The artist and engraver is Thomas Malton Yr. (1748-1804), and architectural draughtsman, who won gold and silver medals for architecture at the RA Schools and moved to Bath in 1780.", sview: "https://goo.gl/maps/KGpPT" },
  { lat: 51.382376, lng: -2.358801, file: "5.jpg", title: "Guildhall", description: "The Guildhall, situated in the High Street, was built between 1766 and 1775 by Thomas Baldwin. The west front had five bays, a pedimented portico and a rusticated ground floor. New wings and a saucer-shaped dome were added by JM Brydon in 1891.", sview: "https://goo.gl/maps/Uwtyr" },
  { lat: 51.384872, lng: -2.361963, file: "4.jpg", title: "Milsom Street", description: "Milsom Street was laid out in the early 1760s to connect the Upper and Lower Town of Bath. It soon became a popular shopping street with a number of high quality shops. Commercial activity in Bath began to shift from the old town to newer areas. Many of the shops had bowed front windows. The Somerset Buildings were designed by Thomas Baldwin and built in 1782. Milsom Street was the fashionable shopping street in Bath: “Do you know I saw the prettiest hat you can imagine in a shop window in Milsom Street just now,” enthuses a friend of Catherine Morland, Jane Austen's heroine in 'Northanger Abbey'.", sview: "https://goo.gl/maps/5UDJk" },
  { lat: 51.386496, lng: -2.362653, file: "7.jpg", title: "Assembly Rooms", description: "The New or Upper Assembly Rooms were built to a design by John Wood the Younger, after a more expensive plan by Robert Adam had been rejected. As the new and fashionable Upper Town had grown in the mid-18th century, the 1708 assembly rooms (also known as the Lower Rooms) were regarded as insufficient. The New Assembly Rooms contained a large tea room, an elegant ballroom and an octagonal card room. It became the hub of social life in Georgian Bath.", sview: "https://goo.gl/maps/jVrbO" },
  { lat: 51.383479, lng: -2.356691, file: "9.jpg", title: "Great Pulteney Street", description: "The unusually wide and elegant street was named after the Earl of Bath, Sir William Pulteney, who ordered its construction. The designer of the classical facades lining the street was Thomas Baldwin, a talented local builder turned architect. He was involved in several of Bath’s notable buildings, including the Pump Room and the Sydney Hotel. Jane Austen lived at 4 Sydney Place, at the end of Great Pulteney Street, with her family from 1801 until 1804.", sview: "https://goo.gl/maps/8FSxP" },
  { lat: 51.379338, lng: -2.358785, file: "10.jpg", title: "Bath Abbey and Pump Rooms", description: "This abbey church was founded in 1499 by Oliver King, Bishop of Bath. It was built by Robert and William Vertue, masons to the king. Bath Abbey is one of the few great late Gothic-style medieval churches whose design has remained unchanged to the present day. This is partly a result of the dissolution of the monastery in the 1530s, which halted construction and let to the church being offered for sale to citizens of Bath for use as a parish church. Eventually the abbey, stripped of its lead and glass, was given to the city free in 1572.", sview: "https://goo.gl/maps/YLlDD" },
  { lat: 51.386220, lng: -2.370417, file: "11.jpg", title: "Royal Crescent", description: "The Royal Crescent in Bath was built in 1767 to a design by John Wood the Younger. The terrace is known as a masterpiece of Georgian architecture with its giant Ionic columns and stately fronts made of freestone. At the time it was established, its location on an isolated, exposed hillside was not universally popular. It became a great success, however, and was used as a model for later housing developments in Bath and other cities. Although all the houses all look the same on the exterior, the interior of each house constructed according to the wishes of the individual client.", sview: "https://goo.gl/maps/AyGYN" },
  { lat: 51.381432, lng: -2.361495, file: "12.jpg", title: "Pump Rooms", description: "", sview: "https://goo.gl/maps/FePgB" },
  { lat: 51.385657, lng: -2.364217, file: "13.jpg", title: "The Circus", description: "The Circus was part of an ambitious scheme to create a classical-style centre in Bath. A circular open space enclosed by crescents of terraced housing, the circus was built between 1754 and 1758 to a design by John Wood the Younger. It was impressively decorated in the Roman style - each building floor was externally decorated by differentiated orders of columns.", sview: "https://goo.gl/maps/G0PSP" },
  { lat: 51.380834, lng: -2.356046, file: "14.jpg", title: "North Parade", description: "The North or Grand Parade was planned as an extension to the city, on a marshy plot of land leading down to the banks of the River Avon. After the site was drained, work was started on the houses along the parade in March 1740. The Palladian scheme for the parade, Pierrepont Street and Duke Street was designed by James Wood the Elder. The north and south parades have since witnessed majory alterations: modern shop fronts have been established, sash bars removed from windows, and the original stone balustrades which surrounded the house fronts have been replaced by iron railings", sview: "https://goo.gl/maps/Ybn2j" },
  { lat: 51.386124, lng: -2.373785, file: "15.jpg", title: "Royal Victoria Park", description: "Royal Victoria Park was laid out by city architect Edward Davis and was opened in honour of Princess Victoria in 1830. The column and gate-piers with lions were set up in 1837.", sview: "https://goo.gl/maps/ojVLA" },
  { lat: 51.380774, lng: -2.360080, file: "2.jpg", title: "Grand Pump Hotel", description: "", sview: "https://goo.gl/maps/yIm0F" },
  { lat: 51.382761, lng: -2.359935, file: "1.jpg", title: "Upper Borough Walls", description: "Upper Borough Walls takes its name from the section of the medieval wall of the city which still remains.", sview: "https://goo.gl/maps/AnGjn" },
  { lat: 51.379068, lng: -2.359743, file: "8.jpg", title: "Southgate Street", description: "", sview: "https://goo.gl/maps/AqGsj" },
];